### ISSUE TITLE
Support decode without url

### ISSUE THREAD

**Issue by Inrixia** [vitalygashkov/dasha#1]
Hi! Thanks for this awesome package, currently I'm decoding a dash.xml but I don't have a valid url to pass.

This is fine since I can just pass it a mock url like `https://test.com` but it would be nice if the url was optional

**Comment by Inrixia** [comment]
I think you misinterpreted this, I was asking about removing the requirement for a url being specified when calling parse.

Eg:
```ts
parse(atob(playbackInfo.manifest), "https://example.com")
```
The manifest I am working with does not have a relevant url so ideally the url would be entirely optional

**Comment by vitalygashkov** [comment]
> I was asking about removing the requirement for a url being specified when calling parse.
> The manifest I am working with does not have a relevant url so ideally the url would be entirely optional

But I did exactly what you're talking about. If I still misunderstood something, please clarify it further.
I've made second parameter (`url`) of the function `parse` optional. Here's the change:
https://github.com/vitalygashkov/dasha/commit/30eed95cc4c80765d57f8062f725acd179860100

During the parsing itself, the presence of base URL remains mandatory (in manifest content), as it is necessary to build URLs for segments.

**Comment by Inrixia** [comment]
Ah never mind! Looks like my types were taking a bit to update :) Thanks again

**Comment by Inrixia** [comment]
Trying to go without the url specified results in this error:

```
Failed to construct 'URL': Invalid URL
```

**Comment by Inrixia** [comment]
Its not a big issue just using a placeholder url thankfully
