### ISSUE TITLE
Query parameters in url not decoding properly

### ISSUE THREAD

**Issue by Inrixia** [vitalygashkov/dasha#2]
Segment urls seem to not be decoding properly, as can be seen below `amp;` is being added after the first parameters.
Thankfully I can easily strip them out but it would be nice if this was fixed thx.

What I am getting:
```
https://REDACTED/REDACTED/0.mp4?Policy=REDACTED&amp;Signature=REDACTED&amp;Key-Pair-Id=REDACTED
```
What I expect:
```
https://REDACTED/REDACTED/0.mp4?Policy=REDACTED&Signature=REDACTED&Key-Pair-Id=REDACTED
```

**Comment by vitalygashkov** [comment]
Can you provide an example of URL to reproduce this issue?

**Comment by Inrixia** [comment]
Just checked and all fixed. Thanks!
